// CHANNELS
// export const CHANNELS_INDEX = 'CHANNELS_INDEX'
// export const CHANNELS_STORE = 'CHANNELS_STORE'

export const CHANNELS_INDEX = 'CHANNELS_INDEX'
export const PUBLISHED_CHANNELS_INDEX = 'CHANNELS_INDEX'
export const LOCAL_CHANNELS_INDEX = 'LOCAL_CHANNELS_INDEX'
export const LOCAL_CHANNELS_STORE = 'LOCAL_CHANNELS_STORE'
export const LOCAL_CHANNELS_CLEAR = 'LOCAL_CHANNELS_CLEAR'
export const LOCAL_CHANNELS_DELETE = 'LOCAL_CHANNELS_DELETE'
export const SEARCH_CHANNELS_INDEX = 'SEARCH_CHANNELS_INDEX'
